### ISSUE TITLE
Dialog feature

### ISSUE THREAD

**Issue by ptrblgh** [pilou/jquery.qzAjax#1]
It would be nice to use dialoges (eg. jQuery dialog).

Example: Before deleting an element, a dialog pops up with confirmation and executing the callback based upon the dialog's button action (del / cancel).

**Comment by Wilzi** [comment]
Default usage:
The data-confirm parameter's value will be the text in default browser confirm

```
<a href="/your-url" class="qzAjax" data-confirm="Are you sure?">Delete</a>
```

You can use custom confirm callback and custom data attribute name in qzAjax init options like below.
You must resolve or reject the confirmPromise jQuery deffered object in your custom confirmAction

```
$('.qzAjax').qzAjax({
      confirmAttributeName: 'custom-confirm',
      confirmAction: function($elem, options, confirmPromise) {
          // create here your awesome confirm dialog
          if (confirm("Sure?")) {
              confirmPromise.resolve();
          } else {
              confirmPromise.reject();
          }
      }
});
```

With this init in your HTML use custom data confirm parameter:

```
<a href="/your-url" class="qzAjax" data-custom-confirm="">Delete</a>
```
